# Generated by Django 3.0.6 on 2020-09-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('imagePath', models.CharField(max_length=5000)),
                ('series_date', models.DateField()),
                ('season', models.IntegerField()),
            ],
        ),
    ]
